export const data = [
    { id: 1, email: 'fofis15650@arpizol.com', type_of_scam: "Survey", report_count: "100", first: "2005", comments: "100" },
    { id: 2, email: 'Beemsee28@jourrapide.com', type_of_scam: "PayPal", report_count: "100", first: "2005", comments: "100" },
    { id: 3, email: 'rnewman@yahoo.ca', type_of_scam: "Mystery Shopper", report_count: "100", first: "2005", comments: "100" },
    { id: 4, email: 'hermanab@outlook.com', type_of_scam: "Quiz", report_count: "100", first: "2005", comments: "100" },
    { id: 5, email: 'stewwy@gmail.com', type_of_scam: "Hidden URL", report_count: "100", first: "2005", comments: "100" },
    { id: 6, email: 'cderoove@verizon.net', type_of_scam: "PayPal", report_count: "100", first: "2005", comments: "100" },
    { id: 7, email: 'uncled@gmail.com', type_of_scam: "Mystery Shopper", report_count: "100", first: "2005", comments: "100" },
    { id: 8, email: 'trygstad@mac.com', type_of_scam: "Quiz", report_count: "100", first: "2005", comments: "100" },
    { id: 9, email: 'fake@gmail.com', type_of_scam: "Hidden URL", report_count: "100", first: "2005", comments: "100" },
    { id: 10, email: 'mastinfo@me.com', type_of_scam: "Mystery Shopper", report_count: "100", first: "2005", comments: "100" },

    { id: 11, email: 'privcan@mac.com', type_of_scam: "Quiz", report_count: "100", first: "2005", comments: "100" },
    { id: 12, email: 'seurat@sbcglobal.net', type_of_scam: "Hidden URL", report_count: "100", first: "2005", comments: "100" },
    { id: 13, email: 'cderoove@verizon.net', type_of_scam: "PayPal", report_count: "100", first: "2005", comments: "100" },
    { id: 14, email: 'campbell@me.com', type_of_scam: "Mystery Shopper", report_count: "100", first: "2005", comments: "100" },
    { id: 15, email: 'barjam@aol.com', type_of_scam: "Quiz", report_count: "100", first: "2005", comments: "100" },
    { id: 16, email: 'itstatus@gmail.com', type_of_scam: "Hidden URL", report_count: "100", first: "2005", comments: "100" },
    { id: 17, email: 'padme@icloud.com', type_of_scam: "PayPal", report_count: "100", first: "2005", comments: "100" },
    { id: 18, email: 'intlprog@gmail.com', type_of_scam: "Mystery Shopper", report_count: "100", first: "2005", comments: "100" },
];