export const data = [
    { id: 1, email: 'fofis15650@arpizol.com', type_of_scam: "Urgent Offer", report_count: "100", first: "2000", comments: "100" },
    { id: 2, email: 'Beemsee28@jourrapide.com', type_of_scam: "PayPal", report_count: "30", first: "2010", comments: "100" },
    { id: 3, email: 'rnewman@yahoo.ca', type_of_scam: "Fake Billing", report_count: "23", first: "2020", comments: "100" },
    { id: 4, email: 'hermanab@outlook.com', type_of_scam: "Fake Virus", report_count: "65", first: "2021", comments: "100" },
    { id: 5, email: 'stewwy@gmail.com', type_of_scam: "Romance", report_count: "43", first: "2000", comments: "100" },
    { id: 6, email: 'cderoove@verizon.net', type_of_scam: "Government", report_count: "1111", first: "2001", comments: "100" },
    { id: 7, email: 'uncled@gmail.com', type_of_scam: "Romance", report_count: "221", first: "2003", comments: "100" },
    { id: 8, email: 'trygstad@mac.com', type_of_scam: "Fake Virus", report_count: "1233", first: "2003", comments: "100" },
    { id: 9, email: 'fake@gmail.com', type_of_scam: "Romance", report_count: "23", first: "2012", comments: "100" },
    { id: 10, email: 'mastinfo@me.com', type_of_scam: "Mystery Shopper", report_count: "1", first: "2015", comments: "100" },

    { id: 11, email: 'privcan@mac.com', type_of_scam: "Tax", report_count: "432", first: "2012", comments: "100" },
    { id: 12, email: 'seurat@sbcglobal.net', type_of_scam: "Hidden URL", report_count: "7777", first: "2017", comments: "100" },
    { id: 13, email: 'cderoove@verizon.net', type_of_scam: "PayPal", report_count: "67", first: "2021", comments: "100" },
    { id: 14, email: 'campbell@me.com', type_of_scam: "Romance", report_count: "865", first: "2020", comments: "100" },
    { id: 15, email: 'barjam@aol.com', type_of_scam: "Property", report_count: "55", first: "2010", comments: "100" },
    { id: 16, email: 'itstatus@gmail.com', type_of_scam: "Romance", report_count: "5", first: "2006", comments: "100" },
    { id: 17, email: 'padme@icloud.com', type_of_scam: "Charity", report_count: "1", first: "2009", comments: "100" },
    { id: 18, email: 'intlprog@gmail.com', type_of_scam: "Money Transfer", report_count: "1231", first: "2005", comments: "100" },
];